// <auto-generated />
using System;
using Hospital.Infrastructure.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.Infrastructure.EF.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    partial class HospitalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Hospital.Domain.Entities.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsFollowUp")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("StartAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DoctorId = 1,
                            IsFollowUp = false,
                            PatientId = 1,
                            RoomNumber = "101",
                            StartAt = new DateTime(2025, 9, 2, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DoctorId = 1,
                            IsFollowUp = false,
                            PatientId = 2,
                            RoomNumber = "101",
                            StartAt = new DateTime(2025, 9, 3, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            DoctorId = 1,
                            IsFollowUp = false,
                            PatientId = 1,
                            RoomNumber = "101",
                            StartAt = new DateTime(2025, 9, 10, 11, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            DoctorId = 2,
                            IsFollowUp = true,
                            PatientId = 3,
                            RoomNumber = "102",
                            StartAt = new DateTime(2025, 8, 20, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            DoctorId = 3,
                            IsFollowUp = true,
                            PatientId = 4,
                            RoomNumber = "103",
                            StartAt = new DateTime(2025, 9, 1, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            DoctorId = 4,
                            IsFollowUp = true,
                            PatientId = 5,
                            RoomNumber = "104",
                            StartAt = new DateTime(2025, 7, 10, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            DoctorId = 5,
                            IsFollowUp = true,
                            PatientId = 6,
                            RoomNumber = "105",
                            StartAt = new DateTime(2025, 9, 16, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            DoctorId = 6,
                            IsFollowUp = false,
                            PatientId = 7,
                            RoomNumber = "101",
                            StartAt = new DateTime(2025, 9, 5, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            DoctorId = 2,
                            IsFollowUp = false,
                            PatientId = 1,
                            RoomNumber = "201",
                            StartAt = new DateTime(2025, 9, 6, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            DoctorId = 3,
                            IsFollowUp = false,
                            PatientId = 1,
                            RoomNumber = "201",
                            StartAt = new DateTime(2025, 9, 7, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            DoctorId = 2,
                            IsFollowUp = false,
                            PatientId = 2,
                            RoomNumber = "202",
                            StartAt = new DateTime(2025, 9, 8, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            DoctorId = 4,
                            IsFollowUp = false,
                            PatientId = 2,
                            RoomNumber = "202",
                            StartAt = new DateTime(2025, 9, 9, 9, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            DoctorId = 2,
                            IsFollowUp = false,
                            PatientId = 3,
                            RoomNumber = "203",
                            StartAt = new DateTime(2025, 9, 10, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            DoctorId = 4,
                            IsFollowUp = false,
                            PatientId = 3,
                            RoomNumber = "203",
                            StartAt = new DateTime(2025, 9, 11, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            DoctorId = 7,
                            IsFollowUp = false,
                            PatientId = 8,
                            RoomNumber = "301",
                            StartAt = new DateTime(2025, 9, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            DoctorId = 7,
                            IsFollowUp = false,
                            PatientId = 9,
                            RoomNumber = "301",
                            StartAt = new DateTime(2025, 9, 15, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            DoctorId = 7,
                            IsFollowUp = false,
                            PatientId = 10,
                            RoomNumber = "301",
                            StartAt = new DateTime(2025, 9, 28, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            DoctorId = 7,
                            IsFollowUp = false,
                            PatientId = 8,
                            RoomNumber = "301",
                            StartAt = new DateTime(2025, 8, 31, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            DoctorId = 8,
                            IsFollowUp = false,
                            PatientId = 9,
                            RoomNumber = "301",
                            StartAt = new DateTime(2025, 10, 1, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            DoctorId = 7,
                            IsFollowUp = false,
                            PatientId = 10,
                            RoomNumber = "302",
                            StartAt = new DateTime(2025, 9, 20, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BirthYear")
                        .HasColumnType("int");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Passport")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Specialization")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BirthYear = 1971,
                            ExperienceYears = 6,
                            FullName = "Doctor 1",
                            Passport = "D000001",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 2,
                            BirthYear = 1972,
                            ExperienceYears = 7,
                            FullName = "Doctor 2",
                            Passport = "D000002",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 3,
                            BirthYear = 1973,
                            ExperienceYears = 8,
                            FullName = "Doctor 3",
                            Passport = "D000003",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 4,
                            BirthYear = 1974,
                            ExperienceYears = 9,
                            FullName = "Doctor 4",
                            Passport = "D000004",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 5,
                            BirthYear = 1975,
                            ExperienceYears = 10,
                            FullName = "Doctor 5",
                            Passport = "D000005",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 6,
                            BirthYear = 1976,
                            ExperienceYears = 11,
                            FullName = "Doctor 6",
                            Passport = "D000006",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 7,
                            BirthYear = 1977,
                            ExperienceYears = 12,
                            FullName = "Doctor 7",
                            Passport = "D000007",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 8,
                            BirthYear = 1978,
                            ExperienceYears = 13,
                            FullName = "Doctor 8",
                            Passport = "D000008",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 9,
                            BirthYear = 1979,
                            ExperienceYears = 14,
                            FullName = "Doctor 9",
                            Passport = "D000009",
                            Specialization = 0
                        },
                        new
                        {
                            Id = 10,
                            BirthYear = 1980,
                            ExperienceYears = 15,
                            FullName = "Doctor 10",
                            Passport = "D000010",
                            Specialization = 0
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Passport")
                        .HasColumnType("longtext");

                    b.Property<string>("Phone")
                        .HasColumnType("longtext");

                    b.Property<int>("Rhesus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Addr1",
                            BirthDate = new DateOnly(1985, 1, 1),
                            BloodGroup = 1,
                            FullName = "Podtyagina Anastasia",
                            Gender = 1,
                            Passport = "P000001",
                            Phone = "111",
                            Rhesus = 0
                        },
                        new
                        {
                            Id = 2,
                            Address = "Addr2",
                            BirthDate = new DateOnly(1990, 2, 2),
                            BloodGroup = 0,
                            FullName = "Yemets Timofey",
                            Gender = 0,
                            Passport = "P000002",
                            Phone = "222",
                            Rhesus = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Addr3",
                            BirthDate = new DateOnly(2000, 3, 3),
                            BloodGroup = 2,
                            FullName = "Astsatryan Liliya",
                            Gender = 0,
                            Passport = "P000003",
                            Phone = "333",
                            Rhesus = 0
                        },
                        new
                        {
                            Id = 4,
                            Address = "Addr4",
                            BirthDate = new DateOnly(1988, 4, 4),
                            BloodGroup = 3,
                            FullName = "Ryzhova Alena",
                            Gender = 1,
                            Passport = "P000004",
                            Phone = "444",
                            Rhesus = 0
                        },
                        new
                        {
                            Id = 5,
                            Address = "Addr5",
                            BirthDate = new DateOnly(1992, 5, 5),
                            BloodGroup = 1,
                            FullName = "Ivanov Daniil",
                            Gender = 0,
                            Passport = "P000005",
                            Phone = "555",
                            Rhesus = 1
                        },
                        new
                        {
                            Id = 6,
                            Address = "Addr6",
                            BirthDate = new DateOnly(1981, 6, 6),
                            BloodGroup = 0,
                            FullName = "Dick Roman",
                            Gender = 0,
                            Passport = "P000006",
                            Phone = "666",
                            Rhesus = 0
                        },
                        new
                        {
                            Id = 7,
                            Address = "Addr7",
                            BirthDate = new DateOnly(1979, 7, 7),
                            BloodGroup = 2,
                            FullName = "Volkov Alexander",
                            Gender = 0,
                            Passport = "P000007",
                            Phone = "777",
                            Rhesus = 0
                        },
                        new
                        {
                            Id = 8,
                            Address = "Addr8",
                            BirthDate = new DateOnly(1995, 8, 8),
                            BloodGroup = 3,
                            FullName = "Klyushin Ivan",
                            Gender = 0,
                            Passport = "P000008",
                            Phone = "888",
                            Rhesus = 1
                        },
                        new
                        {
                            Id = 9,
                            Address = "Addr9",
                            BirthDate = new DateOnly(1998, 9, 9),
                            BloodGroup = 1,
                            FullName = "Semenova Alexandra",
                            Gender = 1,
                            Passport = "P000009",
                            Phone = "999",
                            Rhesus = 0
                        },
                        new
                        {
                            Id = 10,
                            Address = "Addr10",
                            BirthDate = new DateOnly(1987, 10, 10),
                            BloodGroup = 0,
                            FullName = "Grishin Nikita",
                            Gender = 0,
                            Passport = "P000010",
                            Phone = "000",
                            Rhesus = 0
                        });
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Appointment", b =>
                {
                    b.HasOne("Hospital.Domain.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Hospital.Domain.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Hospital.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
