<Project Sdk="Microsoft.NET.Sdk">

	<Sdk Name="Aspire.AppHost.Sdk" Version="9.5.2" />
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsAspireHost>true</IsAspireHost>
		<UserSecretsId>61d9a238-8673-4414-b9df-7ad8d4a78c67</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.AppHost" Version="9.5.2" />
		<PackageReference Include="Aspire.Hosting.MySql" Version="9.5.2" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hospital.Api.Host\Hospital.Api.Host.csproj" />
	</ItemGroup>
</Project>