<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Aspire.NATS.Net" Version="9.4.1" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.0" />
		<PackageReference Include="NATS.Client.Core" Version="2.6.11" />
		<PackageReference Include="Bogus" Version="*" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hospital.Application.Contracts\Hospital.Application.Contracts.csproj" />
		<ProjectReference Include="..\Hospital.ServiceDefaults\Hospital.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>
