<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="NATS.Client.Core" Version="2.6.11" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Hospital.Application\Hospital.Application.csproj" />
		<ProjectReference Include="..\Hospital.Application.Contracts\Hospital.Application.Contracts.csproj" />
		<ProjectReference Include="..\Hospital.Generator.Nats.Host\Hospital.Generator.Nats.Host.csproj" />
		<ProjectReference Include="..\Hospital.Infrastructure.EF\Hospital.Infrastructure.EF.csproj" />
	</ItemGroup>

</Project>