using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Threading.Tasks;

namespace Hospital.Domain.Entities;
/// <summary>
/// Represents a scheduled appointment between a patient and a doctor.
/// </summary>
public class Appointment
{
    /// <summary>
    /// Primary key (auto-generated by database).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Date and time when the appointment starts.
    /// </summary>
    public required DateTime StartAt { get; set; }

    /// <summary>
    /// Room number where the appointment takes place.
    /// </summary>
    public required string RoomNumber { get; set; }

    /// <summary>
    /// True if this appointment is a follow-up, false otherwise.
    /// </summary>
    public bool IsFollowUp { get; set; }

    /// <summary>
    /// Foreign key: ID of the patient.
    /// </summary>
    public required int PatientId { get; set; }

    /// <summary>
    /// Navigation property to the patient.
    /// </summary>
    public required Patient Patient { get; set; }

    /// <summary>
    /// Foreign key: ID of the doctor.
    /// </summary>
    public required int DoctorId { get; set; }

    /// <summary>
    /// Navigation property to the doctor.
    /// </summary>
    public required Doctor Doctor { get; set; }
}
