namespace Hospital.Domain.Entities;
/// <summary>
/// Represents a scheduled appointment between a patient and a doctor.
/// </summary>
public class Appointment
{
    /// <summary>
    /// Primary key (auto-generated by database).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Date and time when the appointment starts.
    /// </summary>
    public DateTime? StartAt { get; set; }

    /// <summary>
    /// Room number where the appointment takes place.
    /// </summary>
    public string? RoomNumber { get; set; }

    /// <summary>
    /// True if this appointment is a follow-up, false otherwise.
    /// </summary>
    public bool IsFollowUp { get; set; }

    /// <summary>
    /// Navigation property to the patient.
    /// </summary>
    public required Patient Patient { get; set; }

    /// <summary>
    /// Navigation property to the doctor.
    /// </summary>
    public required Doctor Doctor { get; set; }
}
