using Hospital.Domain.Enums;

namespace Hospital.Domain.Entities;
/// <summary>
/// Represents a doctor working in the clinic.
/// </summary>
public class Doctor
{
    /// <summary>
    /// Primary key (auto-generated by database).
    /// </summary>
    public int Id { get; set; }

    /// <summary>
    /// Passport number of the doctor.
    /// </summary>
    public required string Passport { get; set; }

    /// <summary>
    /// Full name of the doctor.
    /// </summary>
    public required string FullName { get; set; }

    /// <summary>
    /// Year of birth.
    /// </summary>
    public required int BirthYear { get; set; }

    /// <summary>
    /// Medical specialization.
    /// </summary>
    public DoctorSpecialization Specialization { get; set; }

    /// <summary>
    /// Number of years of work experience.
    /// </summary>
    public required int ExperienceYears { get; set; }

    /// <summary>
    /// Collection of appointments assigned to this doctor.
    /// </summary>
    public ICollection<Appointment> Appointments { get; set; } = [];
}